version: "3.1"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpw
    ports:
      - "5050:80"
    volumes:
      - "./pgadmin/var/lib/pgadmin:/var/lib/pgadmin"
    networks:
      - my_net

  python-app:
    build:
      context: ./Python
      dockerfile: Dockerfile
    container_name: python-app
    image: python:latest
    volumes:
      - ./Python/scripts:/app
    working_dir: /app
    networks:
      - my_net

networks:
  my_net:
    external: true
