version: "3.1"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: makhtar
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    networks:
      - my_net

networks:
  my_net:
    name: my_net